-- MySQL Script generated by MySQL Workbench
-- Tue Aug 16 00:27:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myFuelMapDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myFuelMapDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myFuelMapDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `myFuelMapDB` ;

-- -----------------------------------------------------
-- Table `myFuelMapDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myFuelMapDB`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myFuelMapDB`.`refueling_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myFuelMapDB`.`refueling_list` (
  `serial_number` INT NOT NULL AUTO_INCREMENT,
  `whoseUserID` INT NOT NULL,
  `date` DATE NOT NULL,
  `car_mileage` INT NOT NULL,
  `liters` VARCHAR(7) NOT NULL,
  `price` INT NOT NULL,
  `to_full?` TINYINT NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`serial_number`),
  UNIQUE INDEX `serial_number_UNIQUE` (`serial_number` ASC) VISIBLE,
  INDEX `userIdForeingKey_idx` (`whoseUserID` ASC) VISIBLE,
  CONSTRAINT `userIdForeingKey`
    FOREIGN KEY (`whoseUserID`)
    REFERENCES `myFuelMapDB`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
